//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Invoice_Equipment = new HashSet<Invoice_Equipment>();
        }
    
        public int Equipment_Id { get; set; }
        public string Equipment_Category { get; set; }
        public string Equipment_Model { get; set; }
        public Nullable<int> Equipment_Make { get; set; }
        public Nullable<int> Inven_SerialNo { get; set; }
        public string Equipment_Name { get; set; }
        public int Rental_ID { get; set; }
    
        public virtual Rental Rental { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Equipment> Invoice_Equipment { get; set; }
    }
}
