//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Invoice_No { get; set; }
        public decimal Amount { get; set; }
        public int Job_ID { get; set; }
        public int Rental_ID { get; set; }
        public int Equipment_ID { get; set; }
        public int Vendor_ID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual User User { get; set; }
        public virtual Job Job { get; set; }
        public virtual Rental Rental { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
